version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hempbis-ai-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - LOG_LEVEL=info
    volumes:
      - ./server/logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - hempbis-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hempbis-ai-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - hempbis-network

  nginx:
    image: nginx:alpine
    container_name: hempbis-ai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/logs/:/var/log/nginx/
      - ./certs:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - hempbis-network

networks:
  hempbis-network:
    driver: bridge

volumes:
  node_modules_frontend:
  node_modules_backend:
