version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hempbis-ai-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - LOG_LEVEL=info
    volumes:
      - ./server/logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - hempbis-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hempbis-ai-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api}
    depends_on:
      backend:
        condition: service_healthy
    # No ports needed here if Coolify handles external mapping to the EXPOSEd port (3000)
    # For local testing without Coolify, you might add:
    # ports:
    #   - "3000:3000"
    networks:
      - hempbis-network

networks:
  hempbis-network:
    driver: bridge

# Removed node_modules_frontend and node_modules_backend volumes as they are generally
# not needed with multi-stage Docker builds that copy only necessary artifacts.
# If you had specific reasons for them (e.g., local development speed with host-mounted modules),
# they could be added back, but for production builds they are often omitted.
volumes: {}
